voice:
  tts:
    enabled: true

channels:
  discord:
    enabled: true
    token: ""
    allowFrom: []

  telegram:
    enabled: true
    token: ""
    allowFrom: []

  signal:
    enabled: true
    accountId: ""
    allowFrom: []

  googlechat:
    enabled: true
    token: ""
    allowFrom: []

  slack:
    enabled: true
    token: ""
    allowFrom: []

  whatsapp:
    enabled: true
    accountId: ""
    allowFrom: []

  imessage:
    enabled: true
    allowFrom: []

  twitter:
    enabled: true
    allowFrom: []
